---
title: "Week 3 Discussion File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Part A: Make edits (no conflict)

```{r partner_1a}
# Partner 1: 
# Run the code below to see the original graph
# Change the code below to make the point color change based on 'cut', and update the theme to theme_bw(). Update the title to include your first name. 

ggplot(data = diamonds, aes(x = carat, y = price)) +
  geom_point()+
  theme_bw()+
  labs(title = "Marianoo was here")
```

```{r partner_2a}
# Partner 2: 
# Run the code below to see the original graph
# Change the code below to make the geom a geom_jitter, and update the theme to theme_light. Update the title to include your first name. 

ggplot(data = diamonds, aes(x = color, y = carat)) +
  geom_jitter() +
  theme_light() +
  labs(title = "Alex was here")
```

## PART B: Make problems

```{r break-it-1}
#Mariano's changes
ggplot(data = diamonds, aes(x = price, y = carat)) +
  geom_point() +
ae-branch
  theme_bw()

# alex's changes
expensive_diamonds <- diamonds %>% 
  filter(price > 1000)

ggplot(data = diamonds, aes(x = price, y = carat)) +
  geom_point() +
  theme_void()

  theme_dark()
main
```

```{r break-it-2}
# alex's changes
only_premium_diamonds <- diamonds %>% 
  filter(cut == "Premium")
```

## END Discussion 3
